/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CurrencyInput {
        "currencySymbol": string;
        "separator": string;
        "valid": boolean;
        "value": string;
    }
}
declare global {
    interface HTMLCurrencyInputElement extends Components.CurrencyInput, HTMLStencilElement {
    }
    var HTMLCurrencyInputElement: {
        prototype: HTMLCurrencyInputElement;
        new (): HTMLCurrencyInputElement;
    };
    interface HTMLElementTagNameMap {
        "currency-input": HTMLCurrencyInputElement;
    }
}
declare namespace LocalJSX {
    interface CurrencyInput {
        "currencySymbol"?: string;
        "separator"?: string;
        "valid"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "currency-input": CurrencyInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "currency-input": LocalJSX.CurrencyInput & JSXBase.HTMLAttributes<HTMLCurrencyInputElement>;
        }
    }
}
